# -*- coding: utf-8 -*-
"""Executive Sales & Profitability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Yeqy_4Pedkr1uaqGcfacJ4xzPI8ew_T

# Global Superstore Performance Analysis: Revenue, Profitability & Customer Insights (2011-2014)

**Gambaran Bisnis / Business Overview**

ID:

Analisis ini mengevaluasi performa penjualan dan profitabilitas Global Superstore selama periode 2011–2014. Tujuannya adalah mengidentifikasi tren pertumbuhan bisnis, performa market, profitabilitas produk, serta nilai pelanggan untuk mendukung pengambilan keputusan strategis.

EN:

This analysis evaluates the sales and profitability performance of Global Superstore between 2011 and 2014. The objective is to identify growth trends, market performance, product profitability, and customer value in order to support strategic business decisions.

**Tools :**
*   Google Colab (SQL + Python Analysis)
*   BigQuery SQLite at Colab
*   Looker Studio (Dashboard)
*   Github (Portfolio Hosting)

**Business Case :**

ID :

Management ingin mengetahui :
1. Bagaimana performa penjualan dan profit penjualan?
2. Apakah bisnis tumbuh dari tahun ke tahun?
3. Negara dan market mana yang memberikan kontribusi terbesar?
4. Produk apa yang paling menguntungkan?
5. Apakah diskon mempengaruhi profit?
6. Segmen customer mana yang paling bernilai?
7. Area mana yang perlu diperhatikan karena profit rendah?

EN :

Management wants to understand :
1. What is the overall sales and profit performance?
2. How has the business grown over time (Year-over-Year)?
3. Which countries and markets are the top contributors to sales and profit?
4. What are the most profitable products?
5. How do discounts affect profit margins?
6. Which customer segments generate the most value?
7. Which regions should be prioritized for improvement due to low or negative profit?

# Connect to GDrive
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Import Library"""

import os
import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

"""# Load Dataset"""

#path definition
path="/content/drive/MyDrive/Portfolio/Global Super Store Dataset/Global_Superstore2.csv"

#Read data
df=pd.read_csv(path, encoding='latin1')

"""## Initial Exploration"""

#Menampilan data teratas / Preview Data

df.head()

#Menampilkan bentuk dataset / Show dataset

df.shape

#Menampilkan informasi data / Showing dataset information

df.info()

#Statistical Summary

df.describe()

"""# Data Cleaning / Data Quality Check

## Missing Value
"""

missing = pd.DataFrame ({
    'total_missing': df.isnull().sum(),
    'perc_missing': (df.isnull().sum()/df.shape[0])*100
    })

missing.sort_values(by='perc_missing', ascending=False)

"""**ID : **Postal code memiliki nilai missing value yang tinggi, namun dikarena tidak berpengaruh apapun pada analisis maka tidak ada data yang perlu diubah

**EN : **The postal code column has a high number of missing values. However, since it does not affect the analysis, no data modifications are required.

## Duplicate Check
"""

#Menghitung jumlah total data duplikat / Calculating the total number of duplicate records
duplicate_count = df.duplicated().sum()

print(f"Total Duplicate Rows: {duplicate_count}")

"""## Standarize/Fix Structural Error

### Standarize Column Name
"""

df.columns = (
    df.columns
      .str.strip()
      .str.replace(' ','_', regex=False)
      .str.replace('-','_', regex=False)
      .str.replace('/','_', regex=False)
)

df.columns

"""### Convert Date Column"""

# Order Date

df['Order_Date'] = pd.to_datetime(
    df['Order_Date'],
    dayfirst=True,
    errors='coerce'
)

# Ship Date

df['Ship_Date'] = pd.to_datetime(
    df['Ship_Date'],
    dayfirst=True,
    errors='coerce'
)

# Validate Date Conversion
df[['Order_Date','Ship_Date']].head()

"""### Change Data Type"""

df = df.astype({'Postal_Code': 'str',
                'Quantity': 'int64'})

"""## Check Outlier"""

# Sales

df['Sales'].describe()

# Profit

df['Profit'].describe()

"""## Create Date Features

### Year
"""

df['Order_Year'] = df['Order_Date'].dt.year

"""### Month Number"""

df['Order_Month'] = df['Order_Date'].dt.month

"""### Month Name"""

df['Order_Month'] = df['Order_Date'].dt.strftime('%B')

"""### Quarter"""

df['Order_Quarter'] = df['Order_Date'].dt.quarter

"""### Year Month"""

df['Year_Month'] = df['Order_Date'].dt.strftime('%Y-%m')

# Check Date Range
print(df['Order_Date'].min())
print(df['Order_Date'].max())

# Check Negative Sales
df[df['Sales'] < 0]

# Check Negative Profit
df[df['Profit'] < 0]

"""## Profit Margin"""

#Create Profit Margin
df['Profit_Margin'] = np.where(
    df['Sales'] != 0,
    (df['Profit'] / df['Sales']) * 100,
    0
)

profit_margin = df[['Sales', 'Profit', 'Profit_Margin']]
profit_margin.head()

"""## Shipping Efficiency"""

df['Shipping_Efficiency'] = np.where(
    (df['Ship_Date'] - df['Order_Date']).dt.days != 0,
    (df['Sales'] / (df['Ship_Date'] - df['Order_Date']).dt.days),
    np.nan  # Assign NaN for cases where Ship_Date and Order_Date are the same, to avoid division by zero
)

shipping_efficiency = df[['Sales', 'Ship_Date', 'Order_Date', 'Shipping_Efficiency']]
shipping_efficiency.head()

"""## Shipping Cost Ratio"""

#Create Shipping Cost Ratio
df['Shipping_Cost_Ratio'] = np.where(
    df['Sales'] != 0,
    (df['Shipping_Cost'] / df['Sales']) * 100,
    0
)

shipping_cost_ratio = df[['Sales', 'Shipping_Cost', 'Shipping_Cost_Ratio']]
shipping_cost_ratio.head()

"""## Delivery Days"""

#Create Delivery Days
df['Delivery_Days'] = (
    df['Ship_Date'] - df['Order_Date']
).dt.days

delivery_days = df[['Order_Date', 'Ship_Date', 'Delivery_Days']]
delivery_days.head()

"""## Final Dataset Validation"""

df.info()

"""# Load data into SQLite"""

conn = sqlite3.connect('superstore.db')

"""# Save Data to SQL Table"""

df.to_sql(
    'superstore',
    conn,
    if_exists='replace',
    index=False
)

# Test Query

query = """
SELECT *
FROM superstore
LIMIT 5
"""

pd.read_sql(query, conn)

"""# Extract Data to csv"""

df.to_csv(
    '/content/drive/MyDrive/Portfolio/Global Super Store Dataset/superstore_clean.csv',
    index=False
)

"""# EDA (Explorasi Data Analysis)

## Data Understanding
"""

#check unique value
for col in [
    'Market',
    'Region',
    'Country',
    'Segment',
    'Category',
    'Sub_Category'
]:
    print(f"{col}: {df[col].nunique()}")

"""## Executive KPI Analysis

### Total Sales
"""

sales = """ SELECT
                round(sum(Sales),2) as total_sales
            FROM superstore
        """
sales=pd.read_sql(sales,conn)
value_sales = sales.iloc[0, 0]

print(f"Total Sales : {value_sales}")

"""### Total Profit"""

profit = """ SELECT
                 round(sum(Profit),2) as total_profit
             FROM superstore
         """
profit=pd.read_sql(profit,conn)
value_profit = profit.iloc[0, 0]

print(f"Total Profit : {value_profit}")

"""### Profit Margin"""

margin = """ SELECT
                 round ((sum(Profit)/sum(Sales))*100,2) as profit_margin
             FROM superstore
         """
margin=pd.read_sql(margin,conn)
value_margin = margin.iloc[0, 0]


print(f"profit margin : {value_margin}%")

"""### Total Orders"""

order = """ SELECT
                 count(distinct Order_ID) as total_order
             FROM superstore
         """
order=pd.read_sql(order,conn)
value_order = order.iloc[0, 0]

print(f"Total Order : {value_order}")

"""### Total Customers"""

cust =""" SELECT
                count(distinct Customer_ID) as total_customer
            FROM superstore
        """
cust=pd.read_sql(cust,conn)
value_cust = cust.iloc[0, 0]

print(f"Total Customer : {value_cust}")

"""### Average Order Value"""

order_value = """ SELECT
                      round(sum(Sales)/count(distinct Order_ID),2) as avg_order_value
                  FROM superstore
              """
order_value=pd.read_sql(order_value,conn)
value_order_value = order_value.iloc[0, 0]

print(f"Average Order Value : {value_order_value}")

"""# Business Analysis

## Sales Trend Analysis by Year
"""

tren = """ SELECT
                 Order_Year,
                 round(sum(Sales),2) as total_sales,
                 round(sum(Profit),2) as total_profit
             FROM superstore
             GROUP BY Order_Year
             ORDER BY Order_Year
         """
tren=pd.read_sql(tren,conn)
tren

# Visualisasi Sales Tren / Sales Trend Visualization

plt.figure(figsize=(10,5))

plt.plot(
    tren['Order_Year'],
    tren['total_sales'],
    marker='o'
)

plt.title('Sales Trend by Year')
plt.xlabel('Year')
plt.ylabel('Sales')

plt.xticks(tren['Order_Year'])

plt.grid(True)

plt.show()

# Visualisasi Profit Tren / Profit Trend Visualization

plt.figure(figsize=(10,5))

plt.plot(
    tren['Order_Year'],
    tren['total_profit'],
    marker='o'
)

plt.title('Profit Trend by Year')
plt.xlabel('Year')
plt.ylabel('Profit')

plt.xticks(tren['Order_Year'])

plt.grid(True)

plt.show()

# Visualisasi Sales vs Profit / Sales vs Profit Visualization

plt.figure(figsize=(10,5))

plt.plot(
    tren['Order_Year'],
    tren['total_sales'],
    marker='o',
    label='Sales'
)

plt.plot(
    tren['Order_Year'],
    tren['total_profit'],
    marker='o',
    label='Profit'
)

plt.title('Sales vs Profit Trend')
plt.xlabel('Year')

plt.xticks(tren['Order_Year'])

plt.legend()

plt.grid(True)

plt.show()

"""## Monthly Trend"""

season = """ SELECT
                 CAST(strftime('%m', Order_Date) AS INTEGER) AS Order_Month_Num,
                 Order_Month,
                 round(sum(Sales),2) as total_sales
             FROM superstore
             GROUP BY Order_Month_Num,
                      Order_Month
             ORDER BY Order_Month_Num
         """
season =pd.read_sql(season,conn)
season

#visualisasi monthly sales tren / Monthly Sales Trend Visualization

# Define monthly_sales DataFrame
monthly_sales = """ SELECT
                        Year_Month,
                        round(sum(Sales),2) as total_sales,
                        round(sum(Profit),2) as total_profit
                    FROM superstore
                    GROUP BY Year_Month
                    ORDER BY Year_Month
                """
monthly_sales = pd.read_sql(monthly_sales, conn)

plt.figure(figsize=(15,6))

plt.plot(
    monthly_sales['Year_Month'],
    monthly_sales['total_sales']
)

plt.title('Monthly Sales Trend')
plt.xlabel('Year Month')
plt.ylabel('Sales')

plt.xticks(rotation=45)

plt.grid(True)

plt.show()

# Visualisasi Monthly Profit Tren / Monthly Profit Trend Visualization

# Redefine monthly_sales DataFrame to ensure 'total_profit' is included
monthly_sales = """ SELECT
                        Year_Month,
                        round(sum(Sales),2) as total_sales,
                        round(sum(Profit),2) as total_profit
                    FROM superstore
                    GROUP BY Year_Month
                    ORDER BY Year_Month
                """
monthly_sales = pd.read_sql(monthly_sales, conn)

plt.figure(figsize=(15,6))

plt.plot(
    monthly_sales['Year_Month'],
    monthly_sales['total_profit']
)

plt.title('Monthly Profit Trend')
plt.xlabel('Year Month')
plt.ylabel('Profit')

plt.xticks(rotation=45)

plt.grid(True)

plt.show()

"""### Seasonality Analysis"""

seasonality = pd.read_sql("""
SELECT
    CAST(strftime('%m', Order_Date) AS INTEGER) AS Order_Month_Num,
    Order_Month,
    ROUND(AVG(Sales),2) AS Avg_Sales
FROM superstore
GROUP BY
    Order_Month_Num,
    Order_Month
ORDER BY Order_Month_Num
""", conn)

seasonality

# Visualisasi Seasonality / Seasonality Visualization
plt.figure(figsize=(10,5))

plt.plot(
    seasonality['Order_Month'],
    seasonality['Avg_Sales'],
    marker='o'
)

plt.title('Average Sales by Month')
plt.xlabel('Month')
plt.ylabel('Average Sales')

plt.grid(True)

plt.show()

"""### Monthly Order Tren"""

monthly_orders = pd.read_sql("""
SELECT
    Year_Month,
    COUNT(DISTINCT Order_ID) AS Total_Orders
FROM superstore
GROUP BY Year_Month
ORDER BY Year_Month
""", conn)

monthly_orders

#visualisasi monthly order tren

plt.figure(figsize=(15,6))

plt.plot(
    monthly_orders['Year_Month'],
    monthly_orders['Total_Orders']
)

plt.title('Monthly Orders Trend')
plt.xlabel('Year Month')
plt.ylabel('Orders')

plt.xticks(rotation=45)

plt.grid(True)

plt.show()

"""### Average Order Value (AOV)"""

aov = pd.read_sql("""
SELECT
    Year_Month,

    ROUND(
        SUM(Sales) /
        COUNT(DISTINCT Order_ID),
    2) AS AOV

FROM superstore

GROUP BY Year_Month

ORDER BY Year_Month
""", conn)

aov.head()

#VISUALISASI AOV
plt.figure(figsize=(15,6))

plt.plot(
    aov['Year_Month'],
    aov['AOV']
)

plt.title('Average Order Value Trend')
plt.xlabel('Year Month')
plt.ylabel('AOV')

plt.xticks(rotation=45)

plt.grid(True)

plt.show()

"""## Market Performance"""

# Profit per Region
market = """ SELECT
                 Region,
                 round(sum(Sales),2) as total_sales,
                 round(sum(Profit),2) as total_profit,
                 round((sum(Profit)/sum(Sales))*100,2) as profit_margin
             FROM superstore
             GROUP BY Market
             ORDER BY total_sales desc
         """
market=pd.read_sql(market,conn)
market

# Profit per Market
mgn = """ SELECT Market,
                 ROUND(SUM(Sales),2) AS total_sales,
                 ROUND(SUM(Profit),2) AS total_profit,
                 ROUND(SUM(Profit)/SUM(Sales)*100,2) AS profit_margin
          FROM superstore
          GROUP BY Market
          ORDER BY sales DESC
       """
mgn=pd.read_sql(mgn,conn)
mgn

"""## Country performance"""

# Top 10 Sales

country_sales=""" SELECT Country,
                         round(sum(Sales),2) as total_sales
                  FROM superstore
                  GROUP BY Country
                  ORDER BY total_sales desc
                  LIMIT 10
              """
country_sales=pd.read_sql(country_sales,conn)
country_sales

# Top 10 Profit

country_profit = """ SELECT Country,
                            ROUND(SUM(Profit),2) AS total_profit,
                            ROUND((SUM(Profit)/SUM(Sales))*100,2) as perc_profit
                    FROM superstore
                    GROUP BY Country
                    ORDER BY total_profit DESC
                    LIMIT 10
                """
country_profit=pd.read_sql(country_profit,conn)
country_profit

"""## Negative Profit Analysis"""

neg_prof = """ SELECT Country,
                      ROUND(SUM(Sales),2) AS sales,
                      ROUND(SUM(Profit),2) AS profit
                FROM superstore
                GROUP BY Country
                HAVING SUM(Profit) < 0
                ORDER BY profit
            """

neg_prof=pd.read_sql(neg_prof,conn)
neg_prof

"""## Customer Segmentation"""

cust_segment = """SELECT Segment,
                         ROUND(SUM(Sales),2) AS sales,
                         ROUND(SUM(Profit),2) AS profit,
                         COUNT(DISTINCT Customer_ID) AS customers
                  FROM superstore
                  GROUP BY Segment
                  ORDER BY sales DESC
                """
cust_segment=pd.read_sql(cust_segment,conn)
cust_segment

a="""SELECT Segment,
       ROUND(SUM(Sales)/COUNT(DISTINCT Customer_ID),2) AS revenue_per_customer
FROM superstore
GROUP BY Segment
ORDER BY revenue_per_customer DESC
"""

a=pd.read_sql(a,conn)
a

"""## Category performance"""

cat_perform = """ SELECT Category,
                          ROUND(SUM(Sales),2) AS sales,
                          ROUND(SUM(Profit),2) AS profit
                  FROM superstore
                  GROUP BY Category
                  ORDER BY sales DESC
              """

cat_perform=pd.read_sql(cat_perform,conn)
cat_perform

cat_margin="""SELECT Category,
            ROUND(SUM(Profit)/SUM(Sales)*100,2) AS margin
     FROM superstore
     GROUP BY Category
     ORDER BY margin DESC
   """

cat_margin=pd.read_sql(cat_margin,conn)
cat_margin

"""## Subcategory performance"""

subcat_perform = """ SELECT Sub_Category,
                             ROUND(SUM(Sales),2) AS sales,
                             ROUND(SUM(Profit),2) AS profit
                      FROM superstore
                      GROUP BY Sub_Category
                      ORDER BY profit DESC
                  """
subcat_perform = pd.read_sql(subcat_perform, conn)
subcat_perform

"""### Negative Profit by Subcategories"""

neg_profit_subcategories = """SELECT
Sub_Category,
ROUND(SUM(Profit),2) AS profit
FROM superstore
GROUP BY Sub_Category
ORDER BY profit
LIMIT 10
"""

neg_profit_subcategories = pd.read_sql(neg_profit_subcategories, conn)
neg_profit_subcategories

"""## Product analysis"""

product_profit = """SELECT
Product_Name,
ROUND(SUM(Profit),2) AS profit
FROM superstore
GROUP BY Product_Name
ORDER BY profit DESC
LIMIT 20
"""
product_profit = pd.read_sql(product_profit, conn)
product_profit

"""## Customer analysis"""

customer_performance = """SELECT
Customer_Name,
ROUND(SUM(Sales),2) AS sales,
ROUND(SUM(Profit),2) AS profit,
COUNT(DISTINCT Order_ID) AS orders
FROM superstore
GROUP BY Customer_Name
ORDER BY sales DESC
LIMIT 20
"""
customer_performance = pd.read_sql(customer_performance, conn)
customer_performance

"""## Discount Impact Analysis"""

discount_profit = """SELECT
Discount,
ROUND(AVG(Profit),2)
AS avg_profit
FROM superstore
GROUP BY Discount
ORDER BY Discount
"""
discount_profit = pd.read_sql(discount_profit, conn)
discount_profit

"""### Discount by Grouping"""

discount_group = """SELECT
CASE
WHEN Discount = 0 THEN 'No Discount'
WHEN Discount <= 0.2 THEN 'Low'
WHEN Discount <= 0.5 THEN 'Medium'
ELSE 'High'
END AS discount_group,

ROUND(SUM(Sales),2) sales,
ROUND(SUM(Profit),2) profit

FROM superstore

GROUP BY discount_group
"""
discount_group = pd.read_sql(discount_group, conn)
discount_group

"""## Shipping Analysis"""

shipping_analysis = """SELECT
Market,
ROUND(SUM(Shipping_Cost),2) AS shipping_cost,
ROUND(SUM(Sales),2) AS sales,
ROUND(SUM(Shipping_Cost)/SUM(Sales)*100,2) AS shipping_ratio

FROM superstore
GROUP BY Market
ORDER BY shipping_ratio DESC
"""

shipping_analysis = pd.read_sql(shipping_analysis, conn)
shipping_analysis

"""## Customer Lifetime Value (Pseudo CLV)"""

customer_clv = """SELECT
Customer_Name,

COUNT(DISTINCT Order_ID)
AS orders,

ROUND(SUM(Sales),2)
AS sales,

ROUND(SUM(Profit),2)
AS profit

FROM superstore

GROUP BY Customer_Name

ORDER BY profit DESC

LIMIT 20
"""

customer_clv = pd.read_sql(customer_clv, conn)
customer_clv

"""# Forecast"""

# Aggregate Monthly Sales

monthly_forecast = pd.read_sql("""
SELECT
    Year_Month,
    SUM(Sales) AS Sales
FROM superstore
GROUP BY Year_Month
ORDER BY Year_Month
""", conn)

monthly_forecast.head()

# Convert Date

monthly_forecast['Year_Month'] = pd.to_datetime(
    monthly_forecast['Year_Month']
)

monthly_forecast = monthly_forecast.rename(
    columns={
        'Year_Month':'ds',
        'Sales':'y'
    }
)

# Forecast with Propet

!pip install prophet

from prophet import Prophet

model = Prophet()

model.fit(monthly_forecast)

# Forecast dalam 12 bulan kedepan

future = model.make_future_dataframe(
    periods=12,
    freq='M'
)

forecast = model.predict(future)

# Visualisasi Forecast

fig = model.plot(forecast)

"""# Executive Summary

**Overall Business Performance:**

| KPI             |     Value |
| --------------- | --------: |
| Total Sales     |   12.64 Mio |
| Total Profit    |    1.47 Mio |
| Profit Margin   |    11.61% |
| Analysis Period | 2011–2014 |

ID:
Perusahaan menghasilkan revenue sebesar 12.64 juta dollar dan profit sebesar 1.47 juta dollar selama periode analisis dengan profit margin sekitar 11.6%.

EN:

The company generated 12.64 Mio dollar in revenue and 1.47 Mio dollars in profit during the analysis period, resulting in an overall profit margin of approximately 11.6%.

**Temuan Utama / Key Findings:**
1. Bisnis bertumbuh tiap tahun/Business grew consistently every year

Sales and Profit Growth

| Year |  Sales   | Profit |
| ---- | -----:   | -----: |
| 2011 | 2.26 Mio | 248.9K |
| 2012 | 2.68 Mio | 307.4K |
| 2013 | 3.41 Mio | 406.9K |
| 2014 | 4.30 Mio | 504.2K |

ID:

Penjualan dan profit meningkat secara konsisten selama periode analisis. Revenue hampir dua kali lipat dari 2.26 juta dollars pada tahun 2011 menjadi 4.30 juta dollars pada tahun 2014, menunjukkan pertumbuhan bisnis yang kuat dan permintaan pelanggan yang terus meningkat.

EN:

Both revenue and profit increased steadily throughout the analysis period. Revenue nearly doubled from 2.26M dollars in 2011 to 4.30M dollars in 2014, indicating strong business expansion and sustained customer demand.

2. APAC menjadi market kontribusi revenue terbesar/APA was the largest revenue contributing market

| Market |  Sales   | Profit |
| ------ | -----:   | -----: |
| APAC   | 3.59 Mio |  436K |
| EU     | 2.94 Mio |  373K |
| US     | 2.30 Mio |  286K |
| LATAM  | 2.16 Mio |  222K |

ID:

APAC menghasilkan revenue dan profit tertinggi dibanding market lainnya sehingga menjadi penggerak utama pertumbuhan bisnis perusahaan.

EN:

APAC generated the highest revenue and profit among all markets, making it the primary growth driver for the business.

3. Technology menjadi kategori paling menguntungkan/Technology was the most profitable category
| Category        |  Sales   | Profit |
| --------------- | -----:   | -----: |
| Technology      | 4.74 Mio |  664K |
| Office Supplies | 3.79 Mio |  518K |
| Furniture       | 4.11 Mio |  285K |

ID:

Technology menghasilkan profit tertinggi meskipun bukan kategori dengan penjualan terbesar. Furniture memiliki penjualan yang tinggi namun profit yang relatif rendah, yang mengindikasikan adanya tantangan pada margin keuntungan.

EN:

Technology delivered the highest profit despite not having the highest sales contribution. Furniture generated strong revenue but significantly lower profitability, suggesting margin challenges.

4. Segmen consumer menjadi segmen pelanggan paling bernilai/Consumer segment was the most valuable customer group
| Segment     |  Sales   | Profit |
| ----------- | -----:   | -----: |
| Consumer    | 6.51 Mio |  749K  |
| Corporate   | 3.82 Mio |  441K  |
| Home Office | 2.31 Mio |  277K  |

ID:

Segmen Consumer menyumbang lebih dari separuh total revenue dan menghasilkan profit terbesar sehingga menjadi segmen pelanggan yang paling bernilai bagi perusahaan.

EN:

Consumer customers contributed more than half of total revenue and generated the highest overall profit, making them the most valuable customer segment.

5. Beberapa negara menghasilkan profit negatif/Several Countries Generated Negative Profit

Top loss-making countries:
| Country     | Profit |
| ----------- | -----: |
| Turkey      |  -98K |
| Nigeria     |  -81K |
| Netherlands |  -41K |
| Honduras    |  -29K |
| Pakistan    |  -22K |

ID:

Walaupun menghasilkan penjualan, beberapa negara mencatat profit negatif. Hal ini mengindikasikan adanya masalah pada strategi harga, kebijakan diskon, biaya logistik, atau efisiensi operasional.

EN:

Despite generating sales, several countries reported negative profitability. This indicates potential issues related to pricing strategy, discount policies, logistics costs, or operational efficiency.

**Business Recommendation:**
1. Expand High-Performing Markets

ID: Tingkatkan investasi dan aktivitas komersial pada market APAC dan EU yang menunjukkan performa penjualan dan profit terbaik.

EN: Increase investment and commercial activities in APAC and EU markets where sales and profitability are strongest.

2. Optimize Furniture Profitability

ID: Tinjau strategi harga, biaya pemasok, dan diskon pada kategori Furniture untuk meningkatkan margin keuntungan.

EN: Review pricing, supplier costs, and discount strategies for Furniture products to improve margins.

3. Strengthen Customer Retention Programs

ID: Fokus mempertahankan pelanggan segmen Consumer karena memberikan kontribusi revenue dan profit terbesar.

EN: Focus on retaining Consumer segment customers, as they generate the largest revenue and profit contribution.

4. Investigate Loss-Making Countries

ID: Lakukan investigasi lebih lanjut pada Turkey, Nigeria, dan negara lain yang merugi untuk menemukan akar penyebab profit negatif.

EN: Conduct deeper analysis on Turkey, Nigeria, and other loss-making countries to identify root causes of negative profitability.

5. Monitor Discount Impact

ID: Evaluasi efektivitas program diskon agar pertumbuhan penjualan tidak mengorbankan profitabilitas perusahaan.

EN: Evaluate discount effectiveness to ensure revenue growth does not come at the expense of profitability.
"""

